[package]
name = "milkdevnew/milk-utils"
version = "1.0.0"
description = "Modules we use in our games"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
authors = ["MilkdevNew"]
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
